apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lonely-elephant-go 
  janus-idp.io/tekton: lonely-elephant-go
  backstage.io/kubernetes-id: lonely-elephant-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lonely-elephant-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  