apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lonely-elephant-go
  janus-idp.io/tekton: lonely-elephant-go
  backstage.io/kubernetes-id: lonely-elephant-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lonely-elephant-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
