apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lonely-elephant-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lonely-elephant-go 
  name: lonely-elephant-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lonely-elephant-go 
